# Generated by Django 5.0.4 on 2024-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    ## aqui podemos observar que essa migration 0002 depende da migration 0001
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobre nome')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
        ),
    ]
